"""
report.py

Generates the full "Investment Decision Report" -- a structured, multi-section
document assembled entirely from already-computed, verified data (no LLM).
Sections: Executive Summary, Recommended Portfolio, Budget Allocation,
Carbon/Equity/Resilience Impact, Trade-off Analysis, Alternative Pareto
Solutions, Zone-Level Breakdown, Decision Rationale.
"""
import pandas as pd
from datetime import date


def generate_report(df: pd.DataFrame, wards: pd.DataFrame, budget_cr: float,
                     balanced: pd.Series, front_df: pd.DataFrame,
                     comparison: pd.DataFrame, audit: dict, rationale: list[dict],
                     equity_weights: tuple[float, float, float]) -> str:
    cw_ids = balanced["selected_projects"].split(";")
    recommended = df[df["project_id"].isin(cw_ids)].copy()

    lines = []
    lines.append("=" * 70)
    lines.append("CARBONWISE \u2014 INFRASTRUCTURE INVESTMENT DECISION REPORT")
    lines.append(f"Generated: {date.today().isoformat()}  |  Pilot city: Chennai")
    lines.append("=" * 70)

    # --- Executive Summary ---
    lines.append("\n1. EXECUTIVE SUMMARY")
    lines.append("-" * 70)
    lines.append(
        f"For an available budget of \u20b9{budget_cr:.1f} crore, CarbonWise recommends "
        f"funding {int(balanced['n_projects'])} of {len(df)} candidate infrastructure "
        f"projects across Chennai's 15 zones, utilising \u20b9{balanced['total_cost_cr']:.1f} crore "
        f"({balanced['total_cost_cr']/budget_cr*100:.0f}% of budget). This portfolio was "
        f"selected via ideal-point distance from a Pareto front of {len(front_df)} "
        f"non-dominated solutions generated by NSGA-II multi-objective optimisation."
    )

    # --- Recommended Portfolio ---
    lines.append("\n2. RECOMMENDED PORTFOLIO")
    lines.append("-" * 70)
    by_category = recommended.groupby("category").agg(
        n=("project_id", "count"), cost=("cost_cr_inr", "sum")
    ).sort_values("cost", ascending=False)
    for cat, row in by_category.iterrows():
        lines.append(f"  {cat}: {int(row['n'])} project(s), \u20b9{row['cost']:.1f} cr")

    # --- Budget Allocation ---
    lines.append("\n3. BUDGET ALLOCATION")
    lines.append("-" * 70)
    lines.append(f"  Total budget:        \u20b9{budget_cr:.1f} cr")
    lines.append(f"  Amount allocated:    \u20b9{balanced['total_cost_cr']:.1f} cr")
    lines.append(f"  Unallocated:         \u20b9{budget_cr - balanced['total_cost_cr']:.1f} cr")
    lines.append(f"  Utilisation:         {balanced['total_cost_cr']/budget_cr*100:.0f}%")

    # --- Impact scores ---
    lines.append("\n4. IMPACT SUMMARY")
    lines.append("-" * 70)
    lines.append(f"  Carbon reduction score:    {balanced['carbon_score']:.0f}")
    lines.append(f"  Climate resilience score:  {balanced['resilience_score']:.0f}")
    lines.append(f"  Equity score:              {balanced['equity_score']:.0f}")
    lines.append(f"  Equity weights used:       vulnerability={equity_weights[0]:.2f}, "
                 f"population_benefited={equity_weights[1]:.2f}, "
                 f"infrastructure_deprivation={equity_weights[2]:.2f}")

    # --- Trade-off analysis ---
    lines.append("\n5. TRADE-OFF ANALYSIS")
    lines.append("-" * 70)
    for point in rationale:
        lines.append(f"  {point['title']}: {point['detail']}")

    # --- Baseline comparison ---
    lines.append("\n6. COMPARISON AGAINST CONVENTIONAL METHODS")
    lines.append("-" * 70)
    for _, row in comparison.iterrows():
        lines.append(f"  {row['method']}: carbon={row['carbon_score']:.0f}, "
                     f"resilience={row['resilience_score']:.0f}, equity={row['equity_score']:.0f}")

    # --- Equity audit ---
    lines.append("\n7. EQUITY AUDIT \u2014 WHO IS BEING LEFT BEHIND")
    lines.append("-" * 70)
    lines.append(f"  Population-proportional target: {audit['target_share_pct']:.0f}% of investment "
                 f"should reach high-vulnerability zones")
    lines.append(f"  Greedy (cost-effectiveness only): {audit['before']['actual_share_pct']:.0f}% "
                 f"(gap {audit['before']['gap_pct_points']:+.0f} pts)")
    lines.append(f"  CarbonWise:                        {audit['after']['actual_share_pct']:.0f}% "
                 f"(gap {audit['after']['gap_pct_points']:+.0f} pts)")

    # --- Alternative Pareto solutions ---
    lines.append("\n8. ALTERNATIVE PARETO-OPTIMAL SOLUTIONS (top 5 by carbon)")
    lines.append("-" * 70)
    top5 = front_df.sort_values("carbon_score", ascending=False).head(5)
    for _, row in top5.iterrows():
        lines.append(f"  Solution {int(row['solution_id'])}: {int(row['n_projects'])} projects, "
                     f"\u20b9{row['total_cost_cr']:.1f} cr | carbon={row['carbon_score']:.0f}, "
                     f"resilience={row['resilience_score']:.0f}, equity={row['equity_score']:.0f}")

    # --- Zone-level breakdown ---
    lines.append("\n9. ZONE-LEVEL BREAKDOWN (recommended portfolio)")
    lines.append("-" * 70)
    zone_summary = recommended.groupby("zone_name").agg(
        n=("project_id", "count"), cost=("cost_cr_inr", "sum")
    ).sort_values("cost", ascending=False)
    for zone, row in zone_summary.iterrows():
        vuln = wards[wards["zone_name"] == zone]["vulnerability_index"].iloc[0]
        lines.append(f"  {zone} (vulnerability={vuln:.2f}): {int(row['n'])} project(s), "
                     f"\u20b9{row['cost']:.1f} cr")

    # --- Full project list ---
    lines.append("\n10. FULL RECOMMENDED PROJECT LIST")
    lines.append("-" * 70)
    for _, row in recommended.sort_values("cost_cr_inr", ascending=False).iterrows():
        lines.append(f"  [{row['project_id']}] {row['project_name']} "
                     f"\u2014 \u20b9{row['cost_cr_inr']:.1f} cr")

    lines.append("\n" + "=" * 70)
    lines.append("End of report. Generated entirely from verified optimizer output;")
    lines.append("no figures in this report were estimated or generated by an LLM.")
    lines.append("=" * 70)

    return "\n".join(lines)


if __name__ == "__main__":
    from preprocessing import preprocess
    from equity_scoring import compute_equity_score
    from optimizer import run_nsga2, pareto_front_to_df, pick_balanced_solution
    from baselines import (equal_split_allocation, greedy_cost_effectiveness_allocation,
                            summarize_portfolio)
    from equity_auditor import audit_report
    from decision_rationale import build_rationale

    df = preprocess()
    df = compute_equity_score(df)
    wards = pd.read_csv("../data/raw/wards.csv")
    budget_cr = 50.0

    res, problem = run_nsga2(df, budget_cr)
    front_df = pareto_front_to_df(res, problem, df)
    balanced = pick_balanced_solution(front_df)

    eq_mask = equal_split_allocation(df, budget_cr)
    greedy_mask = greedy_cost_effectiveness_allocation(df, budget_cr)
    cw_ids = balanced["selected_projects"].split(";")
    cw_mask = df["project_id"].isin(cw_ids)
    comparison = pd.DataFrame([
        summarize_portfolio(df, eq_mask, "Equal Split"),
        summarize_portfolio(df, greedy_mask, "Greedy Cost-Effectiveness"),
        summarize_portfolio(df, cw_mask, "CarbonWise"),
    ])
    greedy_ids = df[greedy_mask]["project_id"].tolist()
    audit = audit_report(df, wards, greedy_ids, cw_ids)
    rationale = build_rationale(front_df, balanced, budget_cr, audit)

    report = generate_report(df, wards, budget_cr, balanced, front_df,
                              comparison, audit, rationale, (0.33, 0.33, 0.34))
    print(report)

    with open("../results/portfolios/investment_decision_report.txt", "w") as f:
        f.write(report)
    print("\n\nSaved -> results/portfolios/investment_decision_report.txt")
